metric: cmd_fvd

paired_dataset:
  # root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/gaoshenyuan/NUSC_outputs/vista_final_infer_waymo_traj_all
  # root: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/outputs_hdd/GROUP_full_action_center_main2_30k/infer_waymo_main2_30k_action_center_split0-01-22-09-21

  root: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/outputs_hdd/GROUP_abl_with_carla_data_no-token_act/abl_with_carla_data_no_token_action_center_split_6
  supp: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/waymo/v2/waymo_val_traj_cmd_v2_sub.json
  freq: 12
  # max_frameid: 25
  # gen_startid: 1
  
  gen_startid: 9  
  # id 8 is the current frame
  # id 9 is the first generation frame (should be evaluated as beginning)

  max_frameid: 33


gpu: 0
batch_size: 32
n_runs: 1
shuffle: True
total_cmds: 4