metric: cmd_fvd

paired_dataset:
  # root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/gaoshenyuan/NUSC_outputs/vista_final_infer_waymo_traj_all
  # root: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/outputs/GROUP_full_action/infer_waymo_main5_joint_stage2_high_action_split8-12-19-14-04

  root: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/outputs/GROUP_full_action
  supp: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/waymo/waymo_val_traj_cmd.json
  freq: 12
  # max_frameid: 25
  # gen_startid: 1
  
  gen_startid: 9  
  # id 8 is the current frame
  # id 9 is the first generation frame (should be evaluated as beginning)

  max_frameid: 33


gpu: 0
batch_size: 32
n_runs: 1
shuffle: True
total_cmds: 3