# * Larger LR: 1e-5 -> 1e-4
# * Action zero-init
# * Action balance
# * Bugfix: skip 3 -> skip 7
# * Condition frames: 0, 3 -> 0, 1, 2, 3
# * Mask out heading: 0.3
# * Use all tokens

args:
  checkpoint_activations: True ## using gradient checkpointing
  model_parallel_size: 1
  experiment_name: nus
  mode: finetune
  load: "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/sat/ckpts/main/main4_resume4_bs2_improved1_not-contained-10-14-03-52"
  

  no_load_rng: True
  # train_iters: 10000
  train_iters: 300000
  eval_iters: 1
  eval_interval: 10000  # * Log video every 100 iterations
  eval_batch_size: 1
  save: ckpts
  save_interval: 4000  # * Save checkpoints
  log_interval: 20   # * Log info

  train_data: [
    "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/youtube_json/YouTube_svd_clip-len-49_interval-10_5M_flow_round2.json",  # * OpenDV
    "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/navsim/token2info_train_list.json"  # * navsim
  ]
  valid_data: [
   "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/navsim/token2info_test_all_list.json" 
  ]

  train_data_weights: [1, 40]
  # * OpenDV: 1, 5M
  # * navsim: 40, 40 * 80k = 3.2M

  split: 1,0,0
  # num_workers: 0  # !!! DEBUG
  num_workers: 8
  force_train: True
  # only_log_video_latents: True
  only_log_video_latents: False

  lr_decay_style: 'constant'  # !!!!!! Using constant LR

data:
    target: data_multi.MultiSourceDataset
    params:
      video_size: [256, 448]

      # video_size: [512, 896]
      fps: 10
      max_num_frames: 49
      skip_frms_num: 7.
      prefix_prompt: "This video depicts a realistic view from the driver's perspective of a car driving on the road."
      
      merge_static: True           # merging static to forward
      exclude_highly_static: True  # exclude highly static
      
      p_mask_out_heading: 0.5     # * Inference: 0.
      p_drop_action_caption: 0.5  # * Inference: 0.

      # # navsim train: {'Moving_Forward': 54414, 'Turning_Right': 9128, 'Turning_Left': 21567}
      n_repeat_of_actions:
        Static: 1
        Moving_Forward: 1
        Turning_Left: 5
        Turning_Right: 5

deepspeed:
  # train_micro_batch_size_per_gpu: 1
  train_micro_batch_size_per_gpu: 2   # * smaller bs for abl, faster per iter
  gradient_accumulation_steps: 1
  steps_per_print: 50
  gradient_clipping: 0.1
  zero_optimization:
    stage: 2
    cpu_offload: false
    contiguous_gradients: false
    overlap_comm: true
    reduce_scatter: true
    reduce_bucket_size: 1000000000
    allgather_bucket_size: 1000000000
    load_from_fp32_weights: false
  zero_allow_untested_optimizer: true
  bf16:
    enabled: False
  fp16:
    enabled: True
    loss_scale: 0
    loss_scale_window: 400
    hysteresis: 2
    min_loss_scale: 1
  optimizer:
    type: sat.ops.FusedEmaAdam
    params:
      lr: 0.0001
      betas: [0.9, 0.95]
      eps: 1e-8
      weight_decay: 1e-4
  activation_checkpointing:
    partition_activations: false
    contiguous_memory_optimization: false
  wall_clock_breakdown: false


model:
  scale_factor: 1.15258426
  disable_first_stage_autocast: true
  not_trainable_prefixes: ['model'] ## Using Lora, conditioners are trainable
  # [model.diffusion_model.xxx]
  # [conditioner.xxx]

  log_keys:
    - txt

  en_and_decode_n_samples_a_time: 1  # * split samples
  en_and_decode_n_frames_a_time: 17  # * split frames
  truncate_n_frames_decode: 8

  cond_inds_sampling: &cond_inds_sampling [0, 1, 2]  # * For log videos
  
  denoiser_config:
    target: sgm.modules.diffusionmodules.denoiser.DiscreteDenoiser
    params:
      num_idx: 1000
      quantize_c_noise: False

      weighting_config:
        target: sgm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
      scaling_config:
        target: sgm.modules.diffusionmodules.denoiser_scaling.VideoScaling
      discretization_config:
        target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization
        params:
          shift_scale: 3.0

  network_config:
    target: dit_video_concat.DiffusionTransformer
    params:
      time_embed_dim: &t_emb_dim 512
      elementwise_affine: True
      num_frames: 49
      time_compressed_rate: 4
      # * For (480, 720), originally supported
      # latent_width: 90
      # latent_height: 60

      # # !!! DEBUG: For (512, 896)
      # latent_width: 112
      # latent_height: 64
      
      # * For (256, 448)
      latent_width: 56
      latent_height: 32

      num_layers: 30
      patch_size: 2
      in_channels: 16
      out_channels: 16
      hidden_size: 1920
      adm_in_channels: 256
      num_attention_heads: 30

      transformer_args:
        checkpoint_activations: True ## using gradient checkpointing
        vocab_size: 1
        max_sequence_length: 64
        layernorm_order: pre
        skip_init: false
        model_parallel_size: 1
        is_decoder: false

      modules:
        pos_embed_config:
          target: dit_video_concat.Basic3DPositionEmbeddingMixin
          params:
            text_length: 235  # TODO: Need to be adjusted with traj feature length
            # * 226 + 9 = 235
            # height_interpolation: 1.875  # * cur_height // 256
            # width_interpolation: 1.875   # * cur_width  // 384

            # # !!! DEBUG: For (512, 896) 
            # height_interpolation: 2.0   # * cur_height // 256
            # width_interpolation:  2.3333   # * cur_width  // 384

            height_interpolation: 1  # * cur_height // 256
            width_interpolation: 1.16666   # * cur_width  // 384

        lora_config: ## Using Lora
          target: sat.model.finetune.lora2.LoraMixin
          params:
            r: 128

        patch_embed_config:
          target: dit_video_concat.ImagePatchEmbeddingMixin
          params:
            text_hidden_size: 4096
            cond_emb_in_dim: *t_emb_dim

        adaln_layer_config:
          target: dit_video_concat.AdaLNMixin
          params:
            qk_ln: True

        final_layer_config:
          target: dit_video_concat.FinalLayerMixin

  conditioner_config:
    target: sgm.modules.GeneralConditioner
    params:
      emb_models:
        # * text enc
        - is_trainable: false
          input_key: txt
          ucg_rate: 0.2  # * Higher dropout rate, to encourage learning from fut_traj
          target: sgm.modules.encoders.modules.FrozenT5Embedder
          params:
            model_dir: "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/ckpts/CogVideoX-2b-sat/t5-v1_1-xxl"
            max_length: 226

        # * traj enc
        - is_trainable: true
          input_key: fut_traj
          ucg_rate: 0.2    # * action (world model) and no-action (planning model)
          target: sgm.modules.encoders.traj_encoder.TrajEncoder
          
          params:
            seq_len: 8
            dim: 1024
            out_dim: 4096
            depth: 2   # * Lower depth, to speed up
            mlp_dim: 2048
            pos_emb: "sine"
            avoid_first_ln: true
            zero_init: true
            use_all_tokens: true  # * 9 tokens

  first_stage_config:
    target: vae_modules.autoencoder.VideoAutoencoderInferenceWrapper
    params:
      cp_size: 1
      ckpt_path: "/cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/ckpts/CogVideoX-2b-sat/vae/3d-vae.pt"
      ignore_keys: [ 'loss' ]

      loss_config:
        target: torch.nn.Identity

      regularizer_config:
        target: vae_modules.regularizers.DiagonalGaussianRegularizer

      encoder_config:
        target: vae_modules.cp_enc_dec.ContextParallelEncoder3D
        params:
          double_z: true
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1, 2, 2, 4 ]
          attn_resolutions: [ ]
          num_res_blocks: 3
          dropout: 0.0
          gather_norm: True

      decoder_config:
        target: vae_modules.cp_enc_dec.ContextParallelDecoder3D
        params:
          double_z: True
          z_channels: 16
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1, 2, 2, 4 ]
          attn_resolutions: [ ]
          num_res_blocks: 3
          dropout: 0.0
          gather_norm: false

  loss_fn_config:
    target: sgm.modules.diffusionmodules.loss.VideoDiffusionLoss  # TODO: Dynamics Enhancement Loss + Per-sample Dynamics Weight (According to flow value?)
    params:
      offset_noise_level: 0

      cond_inds: 
        - []
        - [0]
        - [0, 1]
        - [0, 1, 2]
      cond_inds_prob:
        - 0.1
        - 0.15
        - 0.15
        - 0.6  # * For [0, 1, 2]

      apply_cond_aug: &cond_aug V2
      sigma_sampler_config:
        target: sgm.modules.diffusionmodules.sigma_sampling.DiscreteSampling
        params:
          uniform_sampling: false
          custom_sampling: true
          num_idx: 1000
          discretization_config:
            target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization
            params:
              shift_scale: 3.0

  sampler_config:
    target: sgm.modules.diffusionmodules.sampling.VPSDEDPMPP2MSampler
    params:
      num_steps: 50  # TODO: Can we use less steps to speed up?? (GameNGen only uses 4)
      verbose: True
      fixed_frames: 3  # [0, 1, 2]
      cond_inds_sampling: *cond_inds_sampling  # [0, 1, 2]
      apply_cond_aug: *cond_aug # * sample aug_t in sampling, all 0
      apply_cond_aug_chunk_inference: 'min'

      discretization_config:
        target: sgm.modules.diffusionmodules.discretizer.ZeroSNRDDPMDiscretization
        params:
          shift_scale: 3.0

      guider_config:
        target: sgm.modules.diffusionmodules.guiders.DynamicCFG
        params:
          scale: 6
          exp: 5
          num_steps: 50