metric: fid
paired_dataset:
  root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/gaoshenyuan/ECCV_outputs/inference_nusc_v2+cmd-merge
  freq: 12
  max_frameid: 25
  gen_startid: 1
gpu: 0
batch_size: 32
n_runs: 1
shuffle: True
freq: 12