metric: cmd_fvd

paired_dataset:
  # root: /cpfs01/shared/opendrivelab/opendrivelab_hdd/gaoshenyuan/NUSC_outputs/vista_final_infer_waymo_traj_all
  root: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/outputs_hdd/GROUP_full_free_center_main2_40k/infer_waymo_main2_40k_free_center_split18-01-22-14-57
  supp: /cpfs01/user/yangjiazhi/workspace/DVGen/CogVideo/custom_data/waymo/v2/waymo_val_traj_cmd_v2_sub.json
  freq: 12
  # max_frameid: 25
  # gen_startid: 1
  
  gen_startid: 9  
  # id 8 is the current frame
  # id 9 is the first generation frame (should be evaluated as beginning)

  max_frameid: 33


gpu: 0
batch_size: 32
n_runs: 1
shuffle: True
total_cmds: 4